name: Acknowledge Issue
on:
  issues:
    types: opened
permissions:
  contents: read

jobs:
  commentor:
    permissions:
      issues: write  # for peter-evans/create-or-update-comment to create or update comment
      pull-requests: write  # for peter-evans/create-or-update-comment to create or update comment
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # v2.2.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Comment to acknowledge issue
        uses: peter-evans/create-or-update-comment@67dcc547d311b736a8e6c5c236542148a47adc3d # v2.1.1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hey @${{ github.event.issue.user.login }} :wave:!
            Thank you so much for reporting the issue/feature request :rotating_light:.
            Someone from SynapseML Team will be looking to triage this issue soon.
            We appreciate your patience.
