name: Sync Pull Request to Azure Boards

on:
  pull_request_target:
    types: [opened, edited, closed]
    branches:
      - master

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # v2.2.1
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: danhellem/github-actions-pr-to-work-item@f43c651eeb8cb434a03a9d6e76696ba444481f12 # master
      env:
        ado_token: '${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}'
        github_token: '${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}'
        ado_organization: 'msdata'
        ado_project: 'A365'
        ado_wit: 'Task'
        ado_active_state: 'In Progress'
        ado_close_state: 'Done'
        ado_area_path: '${{ secrets.ADO_AREA_PATH }}'
        debug: true
