name: Sync issue to Azure DevOps work item

on:
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # v2.2.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: mhamilton723/github-actions-issue-to-work-item@9bd9d44197557fd55cc7043512a84ea7aa4489d3 # master
        env:
          ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}"
          github_token: "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"
          ado_organization: "msdata"
          ado_project: "A365"
          ado_area_path: '${{ secrets.ADO_AREA_PATH }}'
          ado_wit: "Task"
          ado_new_state: "To Do"
          ado_active_state: "In Progress"
          ado_close_state: "Done"
          ado_bypassrules: true
