name: Clean ACR

# Notes: To access key vault and grab the connection string, we first need a service principal.
# We need to add that service principal as a Reader in the RBAC for the key vault in question,
# as well as adding it with Get and List permissions in the key vault's access policies.
# Then we need to store that service principal's info as a GitHub secret.
# We then use that secret here as the credentials for logging into Azure.
# Instructions are here: https://learn.microsoft.com/en-us/azure/developer/github/github-key-vault
# In our case, the service principal is called synapseml-clean-acr.
# The github secret is a repository secret called clean_acr.
# It is backed up in the mmlspark-keys vault by secret clean-acr-github-actions-info.
# The secret has an expiration date (currently 11/20/2024), so it will need to be renewed at some point.

on:
  schedule:
    - cron: "0 1 * * 0" # every sunday at 1am

# Use workflow_dispatch in place of schedule for debugging.
# You can trigger the workflow in the 'Actions' tab in github.
# Apparently, this file must be in the master branch to get the 'Run workflow' button.
#on:
#  workflow_dispatch:
   
permissions:
  contents: read

jobs:
  clean-acr:
     name: Clean ACR
     runs-on: ubuntu-latest
     steps:
       - name: Harden Runner
         uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # v2.2.1
         with:
           egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

       - name: Azure Login
         uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2 # v1.4.7
         with:
           creds: ${{ secrets.clean_acr }}
       - name: checkout repo content
         uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0 # checkout the repo
       - name: setup python
         uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4.5.0
         with:
           python-version: '3.x'
       - name: Execute clean-acr.py
         uses: azure/CLI@fa0f960f00db49b95fdb54328a767aee31e80105 # v1.0.7
         with:
           inlineScript: |
             python -m venv acr-env
             source acr-env/bin/activate
             pip install --upgrade pip
             pip install azure-storage-blob azure-identity azure-keyvault-secrets
             python .github/workflows/scripts/clean-acr.py mmlspark-keys clean-acr-connection-string
