name: Reopen closed issue on comment

on:
  issue_comment:
    types:
      - created


permissions:
  contents: read

jobs:
  reopen_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write 
      statuses: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # v2.2.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Print context
        run: |
          echo "$GITHUB_CONTEXT"
      - name: Reopen Issue
        run: |
          curl \
          -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
          -d '{"state":"open"}' \
          --fail
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}

      
